import express, { NextFunction, Request, Response } from 'express';
import dotenv from 'dotenv';
import { getAddress, isAddress, type Address } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import {
  BatchFacilitatorClient,
  createGatewayMiddleware,
  isBatchPayment,
} from '@circlefin/x402-batching/server';
import { callHermes } from './lib/hermes';
import { fetchLiveData } from './lib/live-data';
import {
  createUserWallet,
  findCircleWalletForUser,
  getCircleWalletForUser,
  getOrCreateWalletSetId,
} from './lib/circleWallet';
import {
  ANALYST_SYSTEM_PROMPT,
  RESEARCH_SYSTEM_PROMPT,
  WRITER_SYSTEM_PROMPT,
} from './lib/agentPrompts';
import { setWalletForUser } from './lib/walletStore';
import { payProtectedResourceServer } from './lib/x402ServerClient';
import { sendGAEvent } from './lib/gaServer';

dotenv.config();

type OrchestratorStep = 'research' | 'analyst' | 'writer';

type ProxyEvent =
  | { type: 'proxy_start'; step: OrchestratorStep }
  | {
      type: 'payment_required';
      step: OrchestratorStep;
      paymentRequiredHeader: string;
    }
  | {
      type: 'proxy_response';
      step: OrchestratorStep;
      status: number;
      transaction?: string;
      data: unknown;
    }
  | { type: 'error'; message: string; step?: OrchestratorStep; status?: number };

const NETWORK_NAME = 'Arc Testnet';
const CHAIN_ID = 5042002;
const ARC_TESTNET_DOMAIN = Number(process.env.GATEWAY_DOMAIN || 26);
const GATEWAY_API_BASE_URL =
  process.env.GATEWAY_API_BASE_URL || 'https://gateway-api-testnet.circle.com/v1';
const MIN_GATEWAY_BALANCE = 1;

const FACILITATOR_PORT = Number(process.env.FACILITATOR_PORT || 3000);
const RESEARCH_PORT = Number(process.env.RESEARCH_AGENT_PORT || 3001);
const ANALYST_PORT = Number(process.env.ANALYST_AGENT_PORT || 3002);
const WRITER_PORT = Number(process.env.WRITER_AGENT_PORT || 3003);
const PUBLIC_PORT = Number(process.env.PORT || 4000);

const FACILITATOR_URL = `http://127.0.0.1:${FACILITATOR_PORT}`;
const RESEARCH_URL = `http://127.0.0.1:${RESEARCH_PORT}/run`;
const ANALYST_URL = `http://127.0.0.1:${ANALYST_PORT}/run`;
const WRITER_URL = `http://127.0.0.1:${WRITER_PORT}/run`;

const AGENT_TIMEOUT_MS = Number(process.env.AGENT_TIMEOUT_MS || 80_000);
const RESEARCH_AGENT_TIMEOUT_MS = Number(
  process.env.RESEARCH_AGENT_TIMEOUT_MS || 140_000,
);
const ANALYST_AGENT_TIMEOUT_MS = Number(
  process.env.ANALYST_AGENT_TIMEOUT_MS || AGENT_TIMEOUT_MS,
);
const WRITER_AGENT_TIMEOUT_MS = Number(
  process.env.WRITER_AGENT_TIMEOUT_MS || AGENT_TIMEOUT_MS,
);
const LIVE_DATA_TIMEOUT_MS = Number(process.env.RESEARCH_LIVE_DATA_TIMEOUT_MS || 5_000);
const SSE_HEARTBEAT_MS = Number(process.env.SSE_HEARTBEAT_MS || 15_000);

const SYSTEM_PROMPTS = {
  research: `You are a research agent. Given a topic, find and summarize key facts, recent developments, and relevant data. Be thorough and factual. Return structured JSON. When the user message includes LIVE DATA, use it for current figures. Do not use training data for prices or recent events when live data is provided. CRITICAL: Never start any line with >. Never use blockquote formatting. Write in clean plain paragraphs.`,
  analyst: `You are an analyst agent. Given raw research data, extract key insights, identify patterns, and provide analytical conclusions. Return structured JSON. Do NOT start any line or sentence with the > symbol. Do NOT use blockquote formatting. Write in clean plain paragraphs.`,
  writer: `You are a writer agent. Given research and analysis, write a clear, well-structured report. Use markdown formatting. Make it professional and readable. CRITICAL FORMATTING RULES: Never use > at the start of any line. Never use blockquote markdown. Write every sentence as plain paragraph text or bullet points with - only. If you use > anywhere it will break the output. Structure the report exactly as follows: # [Topic] — Research Report; **Prepared by:** AgentFlow AI; ---; ## Executive Summary (2-3 sentence overview); ## Key Facts (clean bullet points); ## Recent Developments (paragraphs, no >); ## Data & Statistics (markdown table where appropriate); ## Analysis (analytical conclusions from analyst agent); ## Conclusion (final summary); ---; Then add exactly one blockquote at the very end: > ⚠️ Disclaimer: This report was generated by AI. Financial figures and statistics may be based on training data and not reflect current values. Always verify with live sources such as CoinMarketCap, CoinGecko, Bloomberg, or Reuters.`,
};

const researchPrice = parsePrice(process.env.RESEARCH_AGENT_PRICE, '0.005');
const analystPrice = parsePrice(process.env.ANALYST_AGENT_PRICE, '0.003');
const writerPrice = parsePrice(process.env.WRITER_AGENT_PRICE, '0.008');

const sellerAddress = resolveSellerAddress();

function parsePrice(input: string | undefined, fallback: string): string {
  return `$${(Number(input || fallback) || Number(fallback)).toFixed(3)}`;
}

function resolveSellerAddress(): Address {
  const configured = process.env.SELLER_ADDRESS?.trim();
  if (configured) {
    if (!isAddress(configured)) {
      throw new Error('SELLER_ADDRESS is configured but invalid.');
    }
    return getAddress(configured);
  }

  const privateKey = process.env.PRIVATE_KEY?.trim();
  if (privateKey) {
    const normalized = (privateKey.startsWith('0x')
      ? privateKey
      : `0x${privateKey}`) as `0x${string}`;
    const account = privateKeyToAccount(normalized);
    console.warn(
      `[Boot] SELLER_ADDRESS is not set. Falling back to address derived from PRIVATE_KEY (${account.address}) for seller pay-to only.`,
    );
    return account.address;
  }

  throw new Error(
    'SELLER_ADDRESS is required when PRIVATE_KEY is not provided. Backend no longer signs buyer payments.',
  );
}

function getErrorMessage(err: unknown): string {
  if (err instanceof Error) return err.message;
  if (typeof err === 'string') return err;
  try {
    return JSON.stringify(err);
  } catch {
    return String(err);
  }
}

function withTimeout<T>(promise: Promise<T>, ms: number, label: string): Promise<T> {
  return new Promise<T>((resolve, reject) => {
    const timer = setTimeout(() => {
      reject(new Error(`${label} timed out after ${ms / 1000}s`));
    }, ms);
    promise
      .then((value) => {
        clearTimeout(timer);
        resolve(value);
      })
      .catch((err) => {
        clearTimeout(timer);
        reject(err);
      });
  });
}

function getAgentResultText(data: { result?: string } | undefined | null): string {
  if (typeof data?.result === 'string' && data.result.trim()) {
    return data.result;
  }
  return JSON.stringify(data ?? {});
}

function createRunId(prefix: string): string {
  return `${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
}

function isAllowedOrigin(origin: string | undefined): boolean {
  if (!origin) return true;
  try {
    const url = new URL(origin);
    const host = url.hostname.toLowerCase();
    if (host === 'localhost' || host === '127.0.0.1') return true;
    if (host.endsWith('.vercel.app')) return true;
    if (url.protocol === 'https:') return true;
    return false;
  } catch {
    return false;
  }
}

function corsMiddleware(req: Request, res: Response, next: NextFunction): void {
  const origin = req.headers.origin;
  const allowed = isAllowedOrigin(typeof origin === 'string' ? origin : undefined);

  if (typeof origin === 'string' && allowed) {
    res.setHeader('Access-Control-Allow-Origin', origin);
    res.setHeader('Vary', 'Origin');
  } else if (!origin) {
    res.setHeader('Access-Control-Allow-Origin', '*');
  }

  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  const requestedHeaders = req.headers['access-control-request-headers'];
  if (typeof requestedHeaders === 'string' && requestedHeaders.trim()) {
    res.setHeader('Access-Control-Allow-Headers', requestedHeaders);
  } else {
    res.setHeader(
      'Access-Control-Allow-Headers',
      'Content-Type, Payment-Signature, Authorization',
    );
  }
  res.setHeader(
    'Access-Control-Expose-Headers',
    'PAYMENT-REQUIRED, PAYMENT-RESPONSE, Content-Type',
  );

  if (req.method === 'OPTIONS') {
    if (origin && !allowed) {
      res.status(403).json({ error: 'Origin not allowed by CORS policy.' });
      return;
    }
    res.sendStatus(204);
    return;
  }

  next();
}

function parseStep(input: string | undefined): OrchestratorStep | null {
  if (input === 'research' || input === 'analyst' || input === 'writer') {
    return input;
  }
  return null;
}

function decodeTransactionFromPaymentResponse(
  paymentResponseHeader: string | null,
): string | undefined {
  if (!paymentResponseHeader) return undefined;
  try {
    const decoded = Buffer.from(paymentResponseHeader, 'base64').toString('utf-8');
    const payload = JSON.parse(decoded) as { transaction?: string };
    return typeof payload.transaction === 'string' ? payload.transaction : undefined;
  } catch {
    return undefined;
  }
}

function getAgentUrl(step: OrchestratorStep): string {
  switch (step) {
    case 'research':
      return RESEARCH_URL;
    case 'analyst':
      return ANALYST_URL;
    case 'writer':
      return WRITER_URL;
  }
}

async function proxyAgentRun(params: {
  step: OrchestratorStep;
  method: 'GET' | 'POST';
  body?: unknown;
  paymentSignature?: string;
}): Promise<{
  status: number;
  data: unknown;
  contentType: string | null;
  paymentRequiredHeader: string | null;
  paymentResponseHeader: string | null;
}> {
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
  };
  if (params.paymentSignature) {
    headers['Payment-Signature'] = params.paymentSignature;
  }

  const response = await fetch(getAgentUrl(params.step), {
    method: params.method,
    headers,
    body: params.method === 'POST' ? JSON.stringify(params.body ?? {}) : undefined,
  });

  const contentType = response.headers.get('content-type');
  const rawBody = await response.text();
  let data: unknown = rawBody;

  if (rawBody && contentType?.includes('application/json')) {
    try {
      data = JSON.parse(rawBody);
    } catch {
      data = rawBody;
    }
  }

  return {
    status: response.status,
    data,
    contentType,
    paymentRequiredHeader: response.headers.get('PAYMENT-REQUIRED'),
    paymentResponseHeader: response.headers.get('PAYMENT-RESPONSE'),
  };
}

async function fetchGatewayBalanceForAddress(address: Address): Promise<{
  available: string;
  total: string;
}> {
  const response = await fetch(`${GATEWAY_API_BASE_URL}/balances`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      token: 'USDC',
      sources: [{ depositor: address, domain: ARC_TESTNET_DOMAIN }],
    }),
  });

  const json = (await response.json().catch(() => ({}))) as {
    balances?: Array<{ balance?: string; withdrawing?: string }>;
    message?: string;
    error?: string;
  };

  if (!response.ok) {
    const details = json.message || json.error || `HTTP ${response.status}`;
    throw new Error(`Gateway API balance fetch failed: ${details}`);
  }

  const first = Array.isArray(json.balances) ? json.balances[0] : undefined;
  const available = first?.balance ?? '0';
  const withdrawing = first?.withdrawing ?? '0';
  const total = (Number(available) + Number(withdrawing)).toString();

  return { available, total };
}

function createFacilitatorApp(): express.Express {
  const app = express();
  app.use(express.json());
  const gatewayClient = new BatchFacilitatorClient();

  app.get('/health', (_req, res) => {
    res.status(200).json({ status: 'ok' });
  });

  app.get('/v1/x402/supported', async (_req, res) => {
    const rid = createRunId('supported');
    try {
      const result = await gatewayClient.getSupported();
      console.log(`[Facilitator ${rid}] supported ok`);
      res.json(result);
    } catch (err) {
      const details = getErrorMessage(err);
      console.error(`[Facilitator ${rid}] /supported failed`, err);
      res
        .status(500)
        .json({ error: 'Internal error during getSupported', details, requestId: rid });
    }
  });

  app.post('/v1/x402/verify', async (req, res) => {
    const rid = createRunId('verify');
    try {
      const { paymentPayload, paymentRequirements } = req.body || {};
      if (!paymentPayload || !paymentRequirements) {
        return res.status(400).json({ error: 'Missing payment data', requestId: rid });
      }
      if (!isBatchPayment(paymentRequirements)) {
        return res.status(400).json({
          error: 'Only Gateway batched payments are supported',
          requestId: rid,
        });
      }
      const result = await gatewayClient.verify(paymentPayload, paymentRequirements);
      if ('isValid' in result && result.isValid === false) {
        console.error(`[Facilitator ${rid}] verify failed`, result.invalidReason ?? result);
      }
      return res.json(result);
    } catch (err) {
      const details = getErrorMessage(err);
      console.error(`[Facilitator ${rid}] /verify failed`, err);
      return res
        .status(500)
        .json({ error: 'Internal error during verify', details, requestId: rid });
    }
  });

  app.post('/v1/x402/settle', async (req, res) => {
    const rid = createRunId('settle');
    try {
      const { paymentPayload, paymentRequirements } = req.body || {};
      if (!paymentPayload || !paymentRequirements) {
        return res.status(400).json({ error: 'Missing payment data', requestId: rid });
      }
      if (!isBatchPayment(paymentRequirements)) {
        return res.status(400).json({
          error: 'Only Gateway batched payments are supported',
          requestId: rid,
        });
      }
      const result = await gatewayClient.settle(paymentPayload, paymentRequirements);
      if (!result.success) {
        console.error(`[Facilitator ${rid}] settle failed`, result.errorReason ?? result);
      }
      return res.json(result);
    } catch (err) {
      const details = getErrorMessage(err);
      console.error(`[Facilitator ${rid}] /settle failed`, err);
      return res
        .status(500)
        .json({ error: 'Internal error during settle', details, requestId: rid });
    }
  });

  return app;
}

function createAgentApp(
  name: OrchestratorStep,
  price: string,
  timeoutMs: number,
  run: (req: Request) => Promise<Record<string, unknown>>,
): express.Express {
  const app = express();
  app.use(express.json());
  const gateway = createGatewayMiddleware({
    sellerAddress,
    facilitatorUrl: FACILITATOR_URL,
  });

  const handler = async (req: Request, res: Response) => {
    const requestId = createRunId(name);
    const start = Date.now();
    try {
      const payload = await withTimeout(run(req), timeoutMs, `${name} agent`);
      console.log(`[Agent ${name} ${requestId}] done in ${Date.now() - start}ms`);
      res.json(payload);
    } catch (err) {
      const details = getErrorMessage(err);
      const status = details.includes('timed out') ? 504 : 500;
      console.error(`[Agent ${name} ${requestId}] failed`, err);
      res.status(status).json({
        error: `${name} agent failed`,
        details,
        requestId,
      });
    }
  };

  app.get('/health', (_req, res) => {
    res.status(200).json({ status: 'ok', agent: name });
  });

  app.get('/run', gateway.require(price), handler);
  app.post('/run', gateway.require(price), handler);

  return app;
}

function createPublicApp(): express.Express {
  const app = express();
  app.use(express.json());
  app.use(corsMiddleware);

  app.get('/health', (_req, res) => {
    res.json({
      status: 'ok',
      agents: ['research', 'analyst', 'writer'],
      network: NETWORK_NAME,
      chainId: CHAIN_ID,
    });
  });

  app.get('/health/stack', (_req, res) => {
    res.json({
      ok: true,
      facilitator: true,
      research: true,
      analyst: true,
      writer: true,
    });
  });

  const getBalanceHandler = async (req: Request, res: Response) => {
    try {
      const addressQuery = req.query.address as string | undefined;
      if (!addressQuery || !isAddress(addressQuery)) {
        return res.status(400).json({ error: 'Valid address query parameter is required.' });
      }

      const address = getAddress(addressQuery);
      const balance = await fetchGatewayBalanceForAddress(address);
      return res.json({
        address,
        balance: balance.available,
        formatted: balance.available,
        total: balance.total,
        network: NETWORK_NAME,
        chainId: CHAIN_ID,
      });
    } catch (err) {
      return res.status(500).json({ error: getErrorMessage(err) });
    }
  };

  app.get('/balance', getBalanceHandler);
  app.get('/gateway-balance', getBalanceHandler);

  app.post('/wallet/create', async (req: Request, res: Response) => {
    try {
      const userAddress = (req.body?.userAddress as string | undefined) ?? '';
      if (!userAddress || !isAddress(userAddress)) {
        return res.status(400).json({ error: 'Valid userAddress is required.' });
      }
      const normalized = getAddress(userAddress);

      const existing = await findCircleWalletForUser(normalized);
      if (existing) {
        return res.json({
          userAddress: normalized,
          circleWalletId: existing.walletId,
          circleWalletAddress: existing.address,
        });
      }

      await getOrCreateWalletSetId();
      const created = await createUserWallet(normalized);

      setWalletForUser(normalized, {
        circleWalletId: created.id,
        circleWalletAddress: created.address,
      });

      return res.json({
        userAddress: normalized,
        circleWalletId: created.id,
        circleWalletAddress: created.address,
      });
    } catch (err) {
      return res.status(500).json({ error: getErrorMessage(err) });
    }
  });

  app.get('/wallet/:address', async (req: Request, res: Response) => {
    try {
      const addressParam = req.params.address;
      if (!addressParam || !isAddress(addressParam)) {
        return res.status(400).json({ error: 'Valid address parameter is required.' });
      }

      const normalized = getAddress(addressParam);
      const existing = await findCircleWalletForUser(normalized);
      if (!existing) {
        return res.status(404).json({ error: 'Wallet not found' });
      }

      return res.json({
        userAddress: normalized,
        circleWalletId: existing.walletId,
        circleWalletAddress: existing.address,
      });
    } catch (err) {
      return res.status(500).json({ error: getErrorMessage(err) });
    }
  });

  app.post('/wallet/fund-gateway', async (req: Request, res: Response) => {
    try {
      const userAddress = (req.body?.userAddress as string | undefined) ?? '';
      if (!userAddress || !isAddress(userAddress)) {
        return res.status(400).json({ error: 'Valid userAddress is required.' });
      }
      const normalized = getAddress(userAddress);

      let existing: { walletId: string; address: string };
      try {
        existing = await getCircleWalletForUser(normalized);
      } catch {
        return res
          .status(404)
          .json({ error: 'Circle wallet not found for user', userAddress: normalized });
      }

      // eslint-disable-next-line no-console
      console.log(
        `[WalletFund] User ${normalized} Circle wallet: ${existing.address} (id=${existing.walletId})`,
      );

      const gatewayBalance = await fetchGatewayBalanceForAddress(existing.address);
      const current = Number(gatewayBalance.available || '0');

      // eslint-disable-next-line no-console
      console.log('[WalletFund] Circle wallet Gateway balance:', current);

      if (Number.isNaN(current)) {
        return res
          .status(500)
          .json({ error: 'Invalid Gateway balance response', balance: gatewayBalance });
      }

      const { transferToGateway } = await import('./lib/circleWallet');

      // eslint-disable-next-line no-console
      console.log('[WalletFund] Calling transferToGateway for wallet:', existing.address);

      const transferResult = await transferToGateway({
        walletId: existing.walletId,
        walletAddress: existing.address,
      });

      const refreshed = await fetchGatewayBalanceForAddress(existing.address);
      const newBalance = Number(refreshed.available || '0');
      const funded = transferResult.status === 'COMPLETE';

      if (!funded) {
        return res.json({
          funded: false,
          amount: transferResult.amount ?? 0,
          transferId: transferResult.transferId,
          transferStatus: transferResult.status,
          approvalId: transferResult.approvalId,
          approvalState: transferResult.approvalState,
          approvalTxHash: transferResult.approvalTxHash,
          depositId: transferResult.depositId,
          depositState: transferResult.depositState,
          depositTxHash: transferResult.depositTxHash,
          errorReason: transferResult.errorReason,
          errorDetails: transferResult.errorDetails,
          newBalance,
          message:
            transferResult.errorDetails ??
            transferResult.errorReason ??
            'Gateway deposit did not complete.',
        });
      }

      return res.json({
        funded,
        amount: transferResult.amount ?? 0,
        transferId: transferResult.transferId,
        transferStatus: transferResult.status,
        approvalId: transferResult.approvalId,
        approvalState: transferResult.approvalState,
        approvalTxHash: transferResult.approvalTxHash,
        depositId: transferResult.depositId,
        depositState: transferResult.depositState,
        depositTxHash: transferResult.depositTxHash,
        errorReason: transferResult.errorReason,
        errorDetails: transferResult.errorDetails,
        newBalance,
      });
    } catch (err) {
      return res.status(500).json({ error: getErrorMessage(err) });
    }
  });

  app.get('/circle-wallet/:userAddress', async (req: Request, res: Response) => {
    try {
      const userAddress = req.params.userAddress ?? '';
      if (!userAddress || !isAddress(userAddress)) {
        return res.status(400).json({ error: 'Valid userAddress is required.' });
      }
      const normalized = getAddress(userAddress);

      const existing = await findCircleWalletForUser(normalized);
      if (!existing) {
        return res
          .status(404)
          .json({ error: 'Circle wallet not found for user', userAddress: normalized });
      }

      const gatewayBalance = await fetchGatewayBalanceForAddress(existing.address);
      const balance = Number(gatewayBalance.available || '0');

      return res.json({
        userAddress: normalized,
        circleWalletId: existing.walletId,
        circleWalletAddress: existing.address,
        gatewayBalance: balance,
        rawGatewayBalance: gatewayBalance,
      });
    } catch (err) {
      return res.status(500).json({ error: getErrorMessage(err) });
    }
  });

  app.post('/deposit', (_req, res) => {
    res.status(410).json({
      success: false,
      error:
        'Deposit is now client-side. Use the browser wallet flow (MetaMask approve + depositFor) instead of backend /deposit.',
    });
  });

  const proxyHandler = async (req: Request, res: Response) => {
    const step = parseStep(req.params.step);
    if (!step) {
      return res
        .status(400)
        .json({ error: 'Invalid step. Use research, analyst, or writer.' });
    }

    const paymentSignature = req.header('Payment-Signature') || undefined;
    try {
      const result = await proxyAgentRun({
        step,
        method: req.method === 'GET' ? 'GET' : 'POST',
        body: req.method === 'GET' ? req.query : req.body,
        paymentSignature,
      });

      if (result.paymentRequiredHeader) {
        res.setHeader('PAYMENT-REQUIRED', result.paymentRequiredHeader);
      }
      if (result.paymentResponseHeader) {
        res.setHeader('PAYMENT-RESPONSE', result.paymentResponseHeader);
      }
      if (result.contentType) {
        res.setHeader('Content-Type', result.contentType);
      }

      if (typeof result.data === 'string') {
        return res.status(result.status).send(result.data);
      }
      return res.status(result.status).json(result.data);
    } catch (err) {
      return res.status(500).json({
        error: `${step} proxy failed`,
        details: getErrorMessage(err),
      });
    }
  };

  app.get('/agent/:step/run', proxyHandler);
  app.post('/agent/:step/run', proxyHandler);

  app.post('/run', async (req, res) => {
    const task = (req.body?.task as string | undefined) ?? '';
    const userAddressInput = (req.body?.userAddress as string | undefined) ?? '';

    res.setHeader('Content-Type', 'text/event-stream');
    res.setHeader('Cache-Control', 'no-cache');
    res.setHeader('Connection', 'keep-alive');
    res.setHeader('X-Accel-Buffering', 'no');
    // @ts-ignore
    res.flushHeaders?.();

    let clientClosed = false;
    const clearHeartbeat = () => {
      clearInterval(heartbeat);
    };
    const handleStreamClosed = () => {
      clientClosed = true;
      clearHeartbeat();
    };
    req.on('aborted', handleStreamClosed);
    res.on('close', handleStreamClosed);

    const sendEvent = (event: Record<string, unknown>) => {
      if (clientClosed || res.writableEnded) return;
      res.write(`data: ${JSON.stringify(event)}\n\n`);
    };

    const heartbeat = setInterval(() => {
      if (clientClosed || res.writableEnded) {
        clearHeartbeat();
        return;
      }
      res.write(`: keep-alive ${Date.now()}\n\n`);
    }, SSE_HEARTBEAT_MS);

    if (!task.trim()) {
      sendEvent({
        type: 'error',
        message: 'Task is required',
      });
      res.end();
      return;
    }

    if (!userAddressInput || !isAddress(userAddressInput)) {
      sendEvent({
        type: 'error',
        message: 'Valid userAddress is required for payment orchestration.',
      });
      res.end();
      return;
    }

    let circleWalletId: string;
    let payerAddress: Address;
    try {
      const normalized = getAddress(userAddressInput);
      const circleWallet = await getCircleWalletForUser(normalized);
      circleWalletId = circleWallet.walletId;
      // Use Circle wallet address as payer, not the user's EOA
      payerAddress = circleWallet.address as Address;
    } catch (err) {
      sendEvent({
        type: 'error',
        message: getErrorMessage(err),
      });
      res.end();
      return;
    }

    try {
      await sendGAEvent('pipeline_started', {
        wallet_address: payerAddress,
        timestamp: Date.now(),
      });

      // Research step
      sendEvent({
        type: 'step_start',
        step: 'research',
        price: researchPrice,
      });

      const researchResult = await payProtectedResourceServer<
        { task?: string; result?: string },
        { task: string }
      >({
        url: RESEARCH_URL,
        method: 'POST',
        body: { task },
        circleWalletId,
        payer: payerAddress,
        chainId: CHAIN_ID,
      });

      const researchTx = researchResult.transaction;
      const researchText = getAgentResultText(researchResult.data);

      sendEvent({
        type: 'step_complete',
        step: 'research',
        tx: researchTx,
        amount: researchPrice,
      });

      await sendGAEvent('research_complete', {
        wallet_address: payerAddress,
        tx: researchTx,
        timestamp: Date.now(),
      });

      // Analyst step
      sendEvent({
        type: 'step_start',
        step: 'analyst',
        price: analystPrice,
      });

      const analystResult = await payProtectedResourceServer<
        { research?: string; result?: string },
        { research: string }
      >({
        url: ANALYST_URL,
        method: 'POST',
        body: { research: researchText },
        circleWalletId,
        payer: payerAddress,
        chainId: CHAIN_ID,
      });

      const analystTx = analystResult.transaction;
      const analysisText = getAgentResultText(analystResult.data);

      sendEvent({
        type: 'step_complete',
        step: 'analyst',
        tx: analystTx,
        amount: analystPrice,
      });

      await sendGAEvent('analyst_complete', {
        wallet_address: payerAddress,
        tx: analystTx,
        timestamp: Date.now(),
      });

      // Writer step
      sendEvent({
        type: 'step_start',
        step: 'writer',
        price: writerPrice,
      });

      const writerResult = await payProtectedResourceServer<
        { research?: string; analysis?: string; result?: string },
        { research: string; analysis: string; task: string }
      >({
        url: WRITER_URL,
        method: 'POST',
        body: {
          research: researchText,
          analysis: analysisText,
          task,
        },
        circleWalletId,
        payer: payerAddress,
        chainId: CHAIN_ID,
      });

      const writerTx = writerResult.transaction;

      sendEvent({
        type: 'step_complete',
        step: 'writer',
        tx: writerTx,
        amount: writerPrice,
      });

      await sendGAEvent('writer_complete', {
        wallet_address: payerAddress,
        tx: writerTx,
        timestamp: Date.now(),
      });

      const total =
        Number(researchPrice.replace('$', '')) +
        Number(analystPrice.replace('$', '')) +
        Number(writerPrice.replace('$', ''));

      sendEvent({
        type: 'receipt',
        total: total.toFixed(3),
        researchPrice,
        analystPrice,
        writerPrice,
        researchTx,
        analystTx,
        writerTx,
      });

      const markdown =
        writerResult.data.result ||
        'Writer agent returned no markdown output.';

      sendEvent({
        type: 'report',
        markdown,
      });

      await sendGAEvent('pipeline_complete', {
        wallet_address: payerAddress,
        total: total.toFixed(3),
        timestamp: Date.now(),
      });
    } catch (err) {
      sendEvent({
        type: 'error',
        message: getErrorMessage(err),
      });
    } finally {
      clearHeartbeat();
      if (!res.writableEnded) res.end();
    }
  });

  return app;
}

async function start(): Promise<void> {
  const facilitatorApp = createFacilitatorApp();
  const researchApp = createAgentApp(
    'research',
    researchPrice,
    RESEARCH_AGENT_TIMEOUT_MS,
    async (req) => {
    const task = (req.body?.task as string) ?? (req.query.task as string) ?? '';
    let liveData = '';
    try {
      liveData = await withTimeout(
        fetchLiveData(task),
        LIVE_DATA_TIMEOUT_MS,
        `Live data timed out after ${LIVE_DATA_TIMEOUT_MS / 1000}s`,
      );
    } catch (liveDataError) {
      console.warn('[Research] Live data enrichment skipped:', getErrorMessage(liveDataError));
    }
    const userMessage = liveData
      ? `LIVE DATA JSON (${new Date().toISOString()}):\n${liveData}\n\nUSER TASK:\n${task}\n\nUse the LIVE DATA JSON above for current figures and dated evidence. Prefer CoinGecko for token market data, DefiLlama for chain TVL and stablecoin liquidity, current-event article snapshots for geopolitical developments, Wikipedia for factual background, and DuckDuckGo only for supporting context.`
      : task;
    return {
      task,
      result: await callHermes(RESEARCH_SYSTEM_PROMPT, userMessage),
    };
  },
  );
  const analystApp = createAgentApp(
    'analyst',
    analystPrice,
    ANALYST_AGENT_TIMEOUT_MS,
    async (req) => {
    const research =
      (req.body?.research as string) ?? (req.query.research as string) ?? '';
    return {
      research,
      result: await callHermes(ANALYST_SYSTEM_PROMPT, research),
    };
  },
  );
  const writerApp = createAgentApp(
    'writer',
    writerPrice,
    WRITER_AGENT_TIMEOUT_MS,
    async (req) => {
    const research =
      (req.body?.research as string) ?? (req.query.research as string) ?? '';
    const analysis =
      (req.body?.analysis as string) ?? (req.query.analysis as string) ?? '';
    const task = (req.body?.task as string) ?? (req.query.task as string) ?? '';
    return {
      research,
      analysis,
      result: await callHermes(
        WRITER_SYSTEM_PROMPT,
        task
          ? `TOPIC:\n${task}\n\nRESEARCH:\n${research}\n\nANALYSIS:\n${analysis}`
          : `RESEARCH:\n${research}\n\nANALYSIS:\n${analysis}`,
      ),
    };
  },
  );
  const publicApp = createPublicApp();

  facilitatorApp.listen(FACILITATOR_PORT, () => {
    console.log(`[Boot] Facilitator listening on :${FACILITATOR_PORT}`);
  });
  researchApp.listen(RESEARCH_PORT, () => {
    console.log(`[Boot] Research agent listening on :${RESEARCH_PORT}`);
  });
  analystApp.listen(ANALYST_PORT, () => {
    console.log(`[Boot] Analyst agent listening on :${ANALYST_PORT}`);
  });
  writerApp.listen(WRITER_PORT, () => {
    console.log(`[Boot] Writer agent listening on :${WRITER_PORT}`);
  });
  publicApp.listen(PUBLIC_PORT, () => {
    console.log(`[Boot] Public API listening on :${PUBLIC_PORT}`);
    console.log(`[Boot] Seller address for x402 payouts: ${sellerAddress}`);
  });
}

start().catch((err) => {
  console.error('[Boot] Failed to start unified backend', err);
  process.exit(1);
});
