import express from 'express';
import dotenv from 'dotenv';
import { privateKeyToAccount } from 'viem/accounts';
import { createGatewayMiddleware } from '@circlefin/x402-batching/server';
import { callHermes } from '../../lib/hermes';

dotenv.config();

const app = express();
app.use(express.json());

const port = Number(process.env.WRITER_AGENT_PORT || 3003);
let privateKey = process.env.PRIVATE_KEY?.trim() ?? '';
if (privateKey && !privateKey.startsWith('0x')) privateKey = `0x${privateKey}`;
const account = privateKeyToAccount(privateKey as `0x${string}`);

const price =
  process.env.WRITER_AGENT_PRICE !== undefined
    ? `$${process.env.WRITER_AGENT_PRICE}`
    : '$0.008';

const facilitatorUrl = process.env.FACILITATOR_URL || 'http://localhost:3000';
const sellerAddress =
  (process.env.SELLER_ADDRESS?.trim() as `0x${string}`) || account.address;
const gateway = createGatewayMiddleware({
  sellerAddress,
  facilitatorUrl,
});

const today = new Date().toISOString().split('T')[0];
const SYSTEM_PROMPT = `Today's date is ${today}. You are a writer agent. Given research and analysis, write a clear, well-structured report. Use markdown formatting. Make it professional and readable. Do NOT start any line or sentence with the > symbol in the report body; do NOT use blockquote formatting in the body. Write in clean plain paragraphs. Structure the report exactly as follows: # [Topic] — Research Report; **Date:** [today's date]; **Prepared by:** AgentFlow AI; ---; ## Executive Summary (2-3 sentence overview); ## Key Facts (clean bullet points); ## Recent Developments (paragraphs, no >); ## Data & Statistics (markdown table where appropriate); ## Analysis (analytical conclusions from analyst agent); ## Conclusion (final summary); ---; Then add exactly one blockquote at the very end: > ⚠️ Disclaimer: This report was generated by AI. Financial figures and statistics may be based on training data and not reflect current values. Always verify with live sources such as CoinMarketCap, CoinGecko, Bloomberg, or Reuters.`;

const runHandler = async (req: express.Request, res: express.Response) => {
  try {
    const research =
      (req.body?.research as string) ?? (req.query.research as string) ?? '';
    const analysis =
      (req.body?.analysis as string) ?? (req.query.analysis as string) ?? '';
    const combinedInput = `RESEARCH:\n${research}\n\nANALYSIS:\n${analysis}`;
    const result = await callHermes(SYSTEM_PROMPT, combinedInput);
    res.json({ research, analysis, result });
  } catch (err) {
    console.error('Writer agent error:', err);
    res.status(500).json({ error: 'Writer agent failed' });
  }
};
app.get('/run', gateway.require(price), runHandler);
app.post('/run', gateway.require(price), runHandler);

app.listen(port, () => {
  console.log(`Writer agent running on :${port}`);
});

